stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Prepare environment for build ..."
    - bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
    - bash build.sh cleanall
    - bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk

    - echo "Start Build u-boot... "
    - bash build.sh uboot

    - echo "Start Build kernel... "
    - bash build.sh kernel

    - echo "Sourcing env setup"
    - source envsetup.sh rockchip_rv1126_vision

    - echo "Start Build buildroot... "
    - bash build.sh -sdk rootfs

    - echo "Start Build recovery... "
    - bash build.sh recovery

    - echo "Prepare images... "
    - bash mkfirmware.sh

    - echo "Prepare update image... "
    - bash build.sh updateimg

    - mkdir -p artifacts
    - cp -L -r rockdev/* artifacts/

    - mkdir -p artifacts_sdk/
    - cp -L rockdev_sdk/vision-sdk.tar.gz artifacts_sdk/

    - echo "Compile complete. All jobs done"

  artifacts:
      paths:
        - artifacts/*
        - artifacts_sdk/*
      expire_in: 2 week    

test-job: # This job runs in the test stage, which runs second.
  stage: test
  allow_failure: true
  needs:
    - job: build-job
      artifacts: true


  script:
    - echo "Run tests ..."
    - bash test_script.sh
