

stages:
  - build

build-ubuntu:
  stage: build
  script:
    - echo "Prepare environment for build ..."
    - bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126-ubuntu.mk
    - bash build.sh cleanall
    - bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126-ubuntu.mk

    - echo "Start Build u-boot... "
    - bash build.sh uboot

    - echo "Start Build kernel... "
    - bash build.sh kernel

    - echo "Start Build Ubuntu rootfs... "
    - bash build.sh ubuntu

    - echo "Start Build recovery... "
    - bash build.sh recovery

    - echo "Prepare images... "
    - bash mkfirmware.sh ubuntu

    - echo "Prepare update image... "
    - bash build.sh updateimg

    - mkdir -p artifacts
    - cp -L -r rockdev/pack/* artifacts/

    - echo "Compile complete. All jobs done"

  artifacts:
      paths:
        - artifacts/*
      expire_in: 2 week        

